# Generated by Django 5.1.6 on 2025-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
