# Generated by Django 5.1.6 on 2025-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_staffprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
    ]
