# Generated by Django 5.1.6 on 2025-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_item_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='found_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
